-- +goose Up

-- System seed migrated from docker/mysql/devops001.sql.
-- This keeps PostgreSQL bootstrap behavior aligned with the original system menus and RBAC data.

DELETE FROM sys_role_menu;
DELETE FROM sys_admin_role;
DELETE FROM sys_menu;
DELETE FROM sys_admin;
DELETE FROM sys_role;
DELETE FROM sys_dept;
DELETE FROM sys_post;

-- sys_post: 6 rows
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (1, 'AAA', '研发总监', 1, '2023-06-14 20:08:22', '主管各个部门');
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (10, 'ops', '运维工程师', 1, '2025-06-28 22:46:33', '运维工程师');
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (11, 'dev', '研发工程师', 1, '2025-06-28 22:50:29', '研发工程师');
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (12, 'test', '测试工程师', 1, '2025-06-28 22:52:57', '测试工程师');
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (14, 'cccc', '运维总监', 1, '2026-01-14 11:12:04', '');
INSERT INTO sys_post (id, post_code, post_name, post_status, create_time, remark) VALUES (15, 'bbb', '测试总监', 1, '2026-01-14 11:12:44', '');

-- sys_dept: 4 rows
INSERT INTO sys_dept (id, parent_id, dept_type, dept_name, dept_status, create_time) VALUES (1, 0, 1, 'AutoOps智能运维公司', 1, '2023-06-14 17:53:23');
INSERT INTO sys_dept (id, parent_id, dept_type, dept_name, dept_status, create_time) VALUES (2, 1, 2, '深圳研发中心1', 1, '2023-06-14 17:53:55');
INSERT INTO sys_dept (id, parent_id, dept_type, dept_name, dept_status, create_time) VALUES (3, 2, 3, '架构设计部门', 1, '2023-06-14 17:54:15');
INSERT INTO sys_dept (id, parent_id, dept_type, dept_name, dept_status, create_time) VALUES (5, 2, 3, '后端研发部门', 1, '2023-06-14 17:55:25');

-- sys_role: 2 rows
INSERT INTO sys_role (id, role_name, role_key, status, description, create_time) VALUES (1, '超级管理员', 'admin', 1, '最大权限', '2023-06-12 20:04:53');
INSERT INTO sys_role (id, role_name, role_key, status, description, create_time) VALUES (13, '游客', 'test', 1, 'test1', '2025-07-03 18:47:25');

-- sys_admin: 2 rows
INSERT INTO sys_admin (id, post_id, dept_id, username, password, nickname, icon, email, phone, note, create_time, status) VALUES (89, 1, 5, 'admin', 'e10adc3949ba59abbe56e057f20f883e', '管理员', 'http://192.168.3.7:8080/api/v1/upload/avatar/20260131/638227000.png', '123456789@qq.com', '13754354536', '后端研发', '2023-05-23 22:15:50', 1);
INSERT INTO sys_admin (id, post_id, dept_id, username, password, nickname, icon, email, phone, note, create_time, status) VALUES (102, 12, 3, 'test', 'e10adc3949ba59abbe56e057f20f883e', '游客', 'http://10.7.16.100:8080/api/v1/upload/avatar/20260130/632084000.png', 'zfwh1024@163.com', '13826541511', '游客', '2025-09-24 12:49:06', 1);

-- sys_admin_role: 2 rows
INSERT INTO sys_admin_role (admin_id, role_id) VALUES (102, 13);
INSERT INTO sys_admin_role (admin_id, role_id) VALUES (89, 1);

-- sys_menu: 203 rows
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (4, 0, '系统管理', 'StarFilled', '', 1, '', 2, 7, '2022-09-04 13:57:39');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (6, 4, '用户信息', 'Avatar', 'base:admin:list', 2, 'system/admin', 2, 1, '2022-09-04 13:59:39');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (7, 4, '角色信息', 'InfoFilled', 'base:role:list', 2, 'system/role', 2, 2, '2022-09-04 14:00:12');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (8, 4, '菜单信息', 'Histogram', 'base:menu:list', 2, 'system/menu', 2, 3, '2022-09-04 14:00:17');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (10, 4, '资产授权', 'Promotion', 'base:post:list', 2, 'system/post', 2, 5, '2022-09-04 14:02:06');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (16, 6, '新增用户', '', 'base:admin:add', 3, '', 2, 1, '2022-09-04 18:32:55');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (17, 6, '修改用户', '', 'base:admin:edit', 3, '', 2, 2, '2022-09-04 18:33:29');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (18, 6, '删除用户', '', 'base:admin:delete', 3, '', 2, 3, '2022-09-04 18:33:51');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (21, 7, '新增角色', '', 'base:role:add', 3, '', 2, 1, '2022-09-04 18:44:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (22, 7, '修改角色', '', 'base:role:edit', 3, '', 2, 2, '2022-09-04 18:45:10');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (23, 7, '删除角色', '', 'base:role:delete', 3, '', 2, 3, '2022-09-04 18:45:46');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (24, 7, '分配权限', '', 'base:role:assign', 3, '', 2, 4, '2022-09-04 18:46:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (26, 8, '新增菜单', '', 'base:menu:add', 3, '', 2, 1, '2022-09-04 18:49:51');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (27, 8, '修改菜单', '', 'base:menu:edit', 3, '', 2, 2, '2022-09-04 18:50:24');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (28, 8, '删除菜单', '', 'base:menu:delete', 3, '', 2, 3, '2022-09-04 18:50:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (32, 10, '新增岗位', '', 'base:post:add', 3, '', 2, 1, '2022-09-04 18:53:28');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (33, 10, '修改岗位', '', 'base:post:edit', 3, '', 2, 2, '2022-09-04 18:53:48');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (34, 10, '删除岗位', '', 'base:post:delete', 3, '', 2, 3, '2022-09-04 18:54:00');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (44, 0, '操作审计', 'BellFilled', '', 1, '', 2, 9, '2022-09-05 11:06:57');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (45, 44, '操作日志', 'User', 'monitor:operator:list', 2, 'monitor/operator', 2, 1, '2022-09-05 11:10:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (46, 44, '登录日志', 'DocumentRemove', 'monitor:loginLog:list', 2, 'monitor/loginlog', 2, 2, '2022-09-05 11:11:31');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (47, 45, '清空操作日志', '', 'monitor:operator:clean', 3, '', 2, 1, '2022-09-05 11:12:36');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (49, 46, '清空登录日志', '', 'monitor:loginLog:clean', 3, '', 2, 1, '2022-09-05 11:16:01');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (60, 6, '重置密码', NULL, 'base:admin:reset', 3, NULL, 2, 6, '2022-12-01 16:33:34');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (62, 46, '删除登录日志', '', 'monitor:loginLog:delete', 3, '', 2, 2, '2022-12-02 15:41:56');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (72, 0, '仪表盘', 'HomeFilled', '', 1, 'dashboard', 2, 1, '2023-05-24 22:11:13');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (73, 45, '删除操作日志', '', 'monitor:operator:delete', 3, '', 2, 3, '2023-06-02 10:09:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (78, 80, '主机管理', 'Platform', 'cmdb:ecs:list', 2, 'cmdb/ecs', 2, 1, '2025-06-29 00:30:35');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (80, 0, '资产管理', 'TrendCharts', '', 1, '', 2, 2, '2025-07-03 11:47:07');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (81, 0, '容器管理', 'UploadFilled', '', 1, '', 2, 3, '2025-07-03 11:50:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (82, 81, '集群管理', 'Menu', 'cloud:k8s:list', 2, 'k8s/list', 2, 1, '2025-07-03 11:56:44');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (83, 81, '节点管理', 'Help', 'cloud:k8s:node', 2, 'k8s/node', 2, 2, '2025-07-03 12:04:59');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (84, 0, '配置中心', 'Tools', '', 1, '', 2, 8, '2025-07-04 17:00:01');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (85, 84, '主机凭据', 'Setting', 'config:ecs:key', 2, 'config/ecskey', 2, 1, '2025-07-04 17:03:10');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (86, 84, '通用凭据', 'User', 'config:accountauth:key', 2, 'config/accountauth', 2, 2, '2025-07-04 17:08:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (88, 80, '网络设备', 'Shop', 'cmdb:switch', 2, 'cmdb/switch', 2, 2, '2025-07-16 15:17:14');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (89, 88, '创建资产', '', 'cmdb:snmp:add', 3, '', 2, 1, '2025-07-18 15:24:31');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (90, 88, '修改资产', '', 'cmdb:snmp:update', 3, '', 2, 2, '2025-07-18 15:25:49');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (91, 88, '删除资产', '', 'cmdb:snmp:delete', 3, '', 2, 3, '2025-07-18 15:26:21');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (93, 81, '工作负载', 'Star', 'cloud:k8s:workload', 2, 'k8s/workload', 2, 4, '2025-07-24 14:38:31');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (95, 80, '数据管理', 'Coin', 'cmdb:db', 2, 'cmdb/db', 2, 3, '2025-07-29 15:27:50');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (96, 44, '数据日志', 'Coin', 'monitor:dblog:list', 2, 'monitor/dblog', 2, 3, '2025-07-31 12:44:07');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (97, 0, '任务中心', 'User', '', 1, '', 2, 5, '2025-08-06 13:33:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (98, 97, '任务模版', 'connection', 'task:template', 2, 'task/template', 2, 2, '2025-08-06 13:35:19');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (99, 97, '任务作业', 'key', 'task:job', 2, 'task/job', 2, 1, '2025-08-06 13:36:06');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (100, 97, 'Ansible任务', 'Eleme', 'task:ansible', 2, 'task/ansible', 2, 3, '2025-08-23 18:35:24');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (101, 0, '运维工具', 'Search', '', 1, '', 2, 6, '2025-08-29 10:59:35');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (102, 101, 'agent 列表', 'price-tag', 'ops:agent', 2, 'ops/agent', 2, 2, '2025-08-29 11:22:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (103, 101, '工具列表', 'present', 'ops:tools', 2, 'ops/tools', 2, 1, '2025-08-29 11:29:02');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (104, 84, '密钥管理', 'Phone', 'config:keymanage:key', 2, 'config/keymanage', 2, 3, '2025-09-08 13:24:40');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (105, 81, '命名空间', 'discount', 'k8s:namespace', 2, 'k8s/namespace', 2, 3, '2025-09-11 15:02:14');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (106, 81, '网络管理', 'guide', 'k8s:network', 2, 'k8s/network', 2, 5, '2025-09-11 15:04:14');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (107, 81, '配置管理', 'connection', 'k8s:config', 2, 'k8s/config', 2, 7, '2025-09-11 15:04:52');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (108, 81, '存储管理', 'Coin', 'k8s:storage', 2, 'k8s/storage', 2, 6, '2025-09-11 15:05:40');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (109, 0, '服务管理', 'ElemeFilled', '', 1, '', 2, 4, '2025-09-16 09:49:55');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (110, 109, '应用列表', 'Menu', 'app:application', 2, 'app/application', 2, 2, '2025-09-16 09:52:58');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (111, 109, '快速发布', 'TrendCharts', 'app:quick-release', 2, 'app/quick-release', 2, 3, '2025-09-16 17:12:11');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (113, 45, '批量删除', '', 'monitor:operator:delete', 3, '', 2, 2, '2025-09-17 20:55:13');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (115, 104, '删除密钥', '', 'config:keymanage:delete', 3, '', 2, 2, '2025-09-18 10:53:44');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (117, 104, '同步主机', '', 'config:keymanage:rsync', 3, '', 2, 3, '2025-09-18 10:57:25');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (118, 104, '创建密钥', '', 'config:keymanage:create', 3, '', 2, 4, '2025-09-18 11:01:12');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (119, 86, '修改账号', '', 'config:common:edit', 3, '', 2, 2, '2025-09-18 11:47:33');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (120, 86, '删除账号', '', 'config:common:delete', 3, '', 2, 3, '2025-09-18 11:48:17');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (121, 86, '解密账号', '', 'config:common:decrypt', 3, '', 2, 4, '2025-09-18 11:48:57');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (122, 86, '创建账号', '', 'config:common:add', 3, '', 2, 1, '2025-09-18 11:49:30');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (123, 85, '修改凭据', '', 'config:ecs:edit', 3, '', 2, 1, '2025-09-18 11:54:16');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (124, 85, '删除凭据', '', 'config:ecs:delete', 3, '', 2, 2, '2025-09-18 11:54:51');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (125, 85, '创建凭据', '', 'config:ecs:create', 3, '', 2, 3, '2025-09-18 11:55:21');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (126, 102, '卸载agent', '', 'ops:agent:delete', 3, '', 2, 1, '2025-09-18 12:47:48');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (127, 102, '查看agent', '', 'ops:agent:get', 3, '', 2, 2, '2025-09-18 12:49:02');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (128, 102, '部署agent', '', 'ops:agent:create', 3, '', 2, 3, '2025-09-18 12:49:56');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (129, 102, '批量卸载agent', '', 'ops:agent:deleteall', 3, '', 2, 4, '2025-09-18 12:50:52');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (130, 100, '启动ansible任务流程', '', 'task:ansible:start', 3, '', 2, 1, '2025-09-18 12:59:30');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (131, 100, '删除ansible任务', '', 'task:ansible:delete', 3, '', 2, 2, '2025-09-18 13:00:03');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (132, 100, '新增ansible任务', '', 'task:ansible:create', 3, '', 2, 3, '2025-09-18 13:00:45');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (133, 98, '新增模版', '', 'task:template:add', 3, '', 2, 1, '2025-09-18 13:16:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (134, 98, '修改模版', '', 'task:template:edit', 3, '', 2, 2, '2025-09-18 13:17:04');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (135, 98, '删除模版', '', 'task:template:delete', 3, '', 2, 3, '2025-09-18 13:18:25');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (136, 99, '新增任务', '', 'task:job:add', 3, '', 2, 1, '2025-09-18 13:24:19');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (137, 99, '启动任务', '', 'task:job:start', 3, '', 2, 2, '2025-09-18 13:24:59');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (138, 99, '删除任务', '', 'task:job:delete', 3, '', 2, 3, '2025-09-18 13:25:41');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (139, 111, '新建发布', '', 'app:quick-release:add', 3, '', 2, 1, '2025-09-18 13:30:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (140, 111, '启动发布', '', 'app:quick-release:start', 3, '', 2, 2, '2025-09-18 13:32:11');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (141, 111, '删除发布', '', 'app:quick-release:delete', 3, '', 2, 3, '2025-09-18 13:32:32');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (142, 110, '创建应用', '', 'app:application:add', 3, '', 2, 1, '2025-09-18 14:28:07');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (143, 110, '修改应用', '', 'app:application:edit', 3, '', 2, 2, '2025-09-18 14:28:59');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (144, 110, '配置应用环境', '', 'app:application:env', 3, '', 2, 3, '2025-09-18 14:29:34');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (145, 110, '删除应用', '', 'app:application:delete', 3, '', 2, 4, '2025-09-18 14:30:11');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (146, 95, '创建数据库账号', '', 'cmdb:db:add', 3, '', 2, 1, '2025-09-18 14:41:32');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (147, 95, '修改数据库配置', '', 'cmdb:db:edit', 3, '', 2, 2, '2025-09-18 14:42:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (148, 95, '删除数据库账号', '', 'cmdb:db:delete', 3, '', 2, 3, '2025-09-18 14:43:57');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (149, 78, '创建主机', '', 'cmdb:ecs:add', 3, '', 2, 1, '2025-09-18 14:47:42');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (150, 78, '主机终端', '', 'cmdb:ecs:terminal', 3, '', 2, 2, '2025-09-18 14:48:36');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (151, 78, '修改主机信息', '', 'cmdb:ecs:edit', 3, '', 2, 3, '2025-09-18 14:49:43');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (152, 78, '上传文件到主机', '', 'cmdb:ecs:upload', 3, '', 2, 4, '2025-09-18 14:50:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (153, 78, '执行主机命令', '', 'cmdb:ecs:shell', 3, '', 2, 5, '2025-09-18 14:51:10');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (154, 78, '监控主机', '', 'cmdb:ecs:monitor', 3, '', 2, 6, '2025-09-18 14:51:52');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (155, 78, '删除主机', '', 'cmdb:ecs:delete', 3, '', 2, 7, '2025-09-18 14:52:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (156, 99, '启动脚本', '', 'task:job:jobstart', 3, '', 2, 4, '2025-09-18 18:36:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (157, 99, '停止脚本', '', 'task:job:jobstop', 3, '', 2, 5, '2025-09-18 18:39:23');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (159, 100, '开始ansible任务作业', '', 'task:ansible:jobstart', 3, '', 2, 4, '2025-09-18 18:43:40');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (160, 111, '启动jenkins任务', '', 'app:quick-release:jobstart', 3, '', 2, 4, '2025-09-18 18:47:39');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (161, 111, '停止jenkins任务', '', 'app:quick-release:jobstop', 3, '', 2, 5, '2025-09-18 18:48:16');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (162, 110, '新增环境', '', 'app:application:envadd', 3, '', 2, 5, '2025-09-18 21:02:28');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (163, 110, '修改环境', '', 'app:application:envedit', 3, '', 2, 6, '2025-09-18 21:03:08');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (164, 110, '删除环境', '', 'app:application:envdelete', 3, '', 2, 7, '2025-09-18 21:04:43');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (165, 78, '连接主机终端', '', 'cmdb:ecs:connecthost', 3, '', 2, 8, '2025-09-18 21:11:43');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (166, 78, '同步主机信息', '', 'cmdb:ecs:rsync', 3, '', 2, 9, '2025-09-19 21:35:06');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (167, 82, '注册集群', '', 'cloud:k8s:register', 3, '', 2, 1, '2025-09-19 21:57:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (168, 82, '创建集群', '', 'cloud:k8s:add', 3, '', 2, 2, '2025-09-19 21:58:19');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (169, 82, '修改集群', '', 'cloud:k8s:edit', 3, '', 2, 3, '2025-09-19 21:59:06');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (170, 82, '同步集群', '', 'cloud:k8s:rsync', 3, '', 2, 4, '2025-09-19 21:59:31');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (171, 82, '删除集群', '', 'cloud:k8s:delete', 3, '', 2, 5, '2025-09-19 21:59:56');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (172, 83, '查看监控仪表盘', '', 'k8s:node:monitor', 3, '', 2, 1, '2025-09-20 00:19:49');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (173, 83, '查看节点资源详情', '', 'k8s:node:details', 3, '', 2, 2, '2025-09-20 00:21:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (178, 105, '创建命名空间', '', 'k8s:namespace:add', 3, '', 2, 1, '2025-09-20 00:36:14');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (179, 105, '查看命名空间详情', '', 'k8s:namespace:details', 3, '', 2, 2, '2025-09-20 00:37:22');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (180, 105, '查看命名空间资源配置', '', 'k8s:namespace:setup', 3, '', 2, 3, '2025-09-20 00:39:05');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (182, 105, '查看限制命名空间资源', '', 'k8s:namespace:restriction', 3, '', 2, 4, '2025-09-20 00:41:25');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (185, 93, '新增工作负载', '', 'k8s:workload:add', 3, '', 2, 1, '2025-09-20 01:05:08');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (192, 93, '回滚工作负载版本', '', 'k8s:workload:rollback_version', 3, '', 2, 8, '2025-09-20 01:39:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (193, 93, '查看pod日志', '', 'k8s:workload:podlog', 3, '', 2, 9, '2025-09-20 01:44:37');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (194, 93, '删除pod', '', 'k8s:workload:poddelete', 3, '', 2, 10, '2025-09-20 01:45:16');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (195, 93, '登陆pod终端', '', 'k8s:workload:terminal', 3, '', 2, 11, '2025-09-20 01:46:07');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (196, 93, '编辑pod yaml文件', '', 'k8s:workload:edityaml', 3, '', 2, 12, '2025-09-20 01:47:22');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (197, 106, '新增service', '', 'k8s:network:addservice', 3, '', 2, 1, '2025-09-20 02:14:21');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (203, 106, '新增ingress', '', 'k8s:network:addingress', 3, '', 2, 2, '2025-09-20 02:27:29');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (207, 109, '服务上线', 'Platform', 'app:service_work', 2, 'app/service_work', 2, 4, '2025-11-20 11:46:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (208, 109, '脚本上线', 'Phone', 'app:sh_release', 2, 'app/sh-release', 2, 5, '2025-11-28 11:13:05');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (212, 0, '监控中心', 'Shop', '', 1, '', 2, 4, '2025-12-03 21:21:04');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (213, 212, '域名监控', 'UploadFilled', 'monitor:domain', 2, 'monitor/domain', 2, 1, '2025-12-03 21:22:11');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (215, 4, '系统配置', 'List', 'system:config', 2, 'system/config', 2, 6, '2025-12-09 11:03:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (216, 212, '故障管理', 'Help', 'monitor:incident', 2, 'monitor/incident', 2, 2, '2025-12-10 15:10:29');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (217, 95, '查看密码', '', 'cmdb:db:passwd', 3, '', 2, 4, '2025-12-13 14:27:22');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (218, 95, '测试链接', '', 'cmdb:db:test', 3, '', 2, 5, '2025-12-13 14:28:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (219, 95, 'DBMS终端', '', 'cmdb:db:dbms', 3, '', 2, 6, '2025-12-13 14:32:59');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (220, 95, 'Redis终端', '', 'cmdb:db:redis', 3, '', 2, 7, '2025-12-13 14:33:27');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (221, 95, 'ES终端', '', 'cmdb:db:es', 3, '', 2, 8, '2025-12-13 14:33:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (222, 95, 'Mongo终端', '', 'cmdb:db:mongo', 3, '', 2, 9, '2025-12-13 14:34:14');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (223, 207, '新建工单', '', 'app:service_work:add', 3, '', 2, 1, '2025-12-13 14:45:07');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (224, 207, '查看工单', '', 'app:service_work:get', 3, '', 2, 2, '2025-12-13 14:51:18');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (225, 207, '删除工单', '', 'app:service_work:delete', 3, '', 2, 3, '2025-12-13 14:52:02');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (226, 208, '新建脚本工单', '', 'app:service_sh:add', 3, '', 2, 1, '2025-12-13 15:11:37');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (227, 208, '查看脚本工单', '', 'app:service_sh:get', 3, '', 2, 2, '2025-12-13 15:14:03');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (228, 208, '删除脚本工单', '', 'app:service_sh:delete', 3, '', 2, 3, '2025-12-13 15:14:29');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (229, 213, '新增域名', '', 'monitor:domain:add', 3, '', 2, 1, '2025-12-13 15:22:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (230, 213, '批量新增域名', '', 'monitor:domain:add_all', 3, '', 2, 2, '2025-12-13 15:23:44');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (231, 213, '域名自动巡检', '', 'monitor:domain:auto_inspection', 3, '', 2, 3, '2025-12-13 15:25:35');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (232, 213, '云导入', '', 'monitor:domain:cloud_import', 3, '', 2, 4, '2025-12-13 15:26:55');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (233, 213, '单域名手动巡检', '', 'monitor:domain:ops_inspection', 3, '', 2, 5, '2025-12-13 15:36:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (234, 213, '编辑域名', '', 'monitor:domain:edit', 3, '', 2, 6, '2025-12-13 15:38:30');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (235, 213, '删除域名', '', 'monitor:domain:delete', 3, '', 2, 7, '2025-12-13 15:38:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (236, 216, '新增故障记录', '', 'monitor:incident:add', 3, '', 2, 1, '2025-12-13 15:55:41');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (237, 216, '编辑故障记录', '', 'monitor:incident:edit', 3, '', 2, 2, '2025-12-13 15:57:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (238, 216, '编辑故障状态', '', 'monitor:incident:status', 3, '', 2, 3, '2025-12-13 15:57:39');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (239, 216, '删除故障记录', '', 'monitor:incident:delete', 3, '', 2, 4, '2025-12-13 15:58:12');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (240, 216, '访问故障链接', '', 'monitor:incident:url', 3, '', 2, 5, '2025-12-13 16:02:46');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (241, 78, '下载文件', '', 'cmdb:ecs:download', 3, '', 2, 10, '2025-12-13 16:13:17');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (242, 109, '应用视图', 'Help', 'app:view', 2, 'app/view', 2, 1, '2025-12-16 11:03:47');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (243, 78, '批量操作', '', 'cmdb:ecs:batch', 3, '', 2, 10, '2025-12-26 19:04:56');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (244, 104, '查看密钥', '', 'config:keymanage:decrypt', 3, '', 2, 5, '2025-12-27 00:20:50');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (245, 88, '监控大盘', '', 'cmdb:snmp:collect', 3, '', 2, 4, '2026-01-01 15:48:05');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (246, 88, '终端按钮', '', 'cmdb:snmp:ssh', 3, '', 2, 5, '2026-01-01 22:18:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (247, 44, '会话录制', 'Coin', 'monitor:recording', 2, 'monitor/recording', 2, 4, '2026-01-08 19:57:24');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (250, 86, '测试连接', '', 'config:common:test', 3, '', 2, 5, '2026-01-18 23:27:29');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (251, 212, '告警配置', 'Help', 'monitor:alert', 2, 'monitor/alert', 2, 3, '2026-01-28 12:45:25');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (252, 251, '新增模板', '', 'monitor:alert:template:add', 3, '', 2, 1, '2026-01-28 14:29:45');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (254, 251, '修改模板', '', 'monitor:alert:template:edit', 3, '', 2, 3, '2026-01-28 14:32:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (256, 251, '告警认领', '', 'monitor:alert:record:acknowledge', 3, '', 2, 5, '2026-01-28 14:34:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (257, 251, '告警处理', '', 'monitor:alert:record:handle', 3, '', 2, 6, '2026-01-28 14:35:49');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (258, 251, 'PromQL预览', '', 'monitor:alert:policy:preview', 3, '', 2, 7, '2026-01-28 14:36:50');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (259, 251, '新增告警策略', '', 'monitor:alert:policy:add', 3, '', 2, 8, '2026-01-28 14:38:20');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (260, 251, '批量删除告警策略', '', 'monitor:alert:policy:delete', 3, '', 2, 9, '2026-01-28 14:39:12');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (261, 251, '修改告警策略', '', 'monitor:alert:policy:edit', 3, '', 2, 10, '2026-01-28 14:40:45');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (262, 251, '删除告警策略', '', 'monitor:alert:policy:delete', 3, '', 2, 11, '2026-01-28 14:41:12');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (263, 251, '配置告警规则', '', 'monitor:alert:policy:rule', 3, '', 2, 11, '2026-01-28 19:49:35');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (264, 251, '新增配置告警规则', '', 'monitor:alert:policy-rule:add', 3, '', 2, 12, '2026-01-28 19:57:15');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (265, 251, '删除配置告警规则', '', 'monitor:alert:policy-rule:delete', 3, '', 2, 13, '2026-01-28 19:57:58');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (266, 251, '激活告警规则', '', 'monitor:alert:policy-rule:status', 3, '', 2, 14, '2026-01-28 19:58:53');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (267, 251, '编辑告警规则', '', 'monitor:alert:policy-rule:edit', 3, '', 2, 15, '2026-01-29 14:44:01');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (268, 212, 'API监控', 'Help', 'monitor:api', 2, 'monitor/api', 2, 4, '2026-02-01 16:51:00');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (269, 268, '批量删除api接口', '', 'monitor:api:delete', 3, '', 2, 1, '2026-02-01 20:56:30');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (270, 268, '查询api接口状态', '', 'monitor:api:status', 3, '', 2, 2, '2026-02-01 20:57:23');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (271, 268, '修改api接口', '', 'monitor:api:edit', 3, '', 2, 3, '2026-02-01 20:57:46');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (272, 268, '删除api接口', '', 'monitor:api:delete', 3, '', 2, 4, '2026-02-01 20:58:10');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (273, 268, '新增api接口', '', 'monitor:api:add', 3, '', 2, 1, '2026-02-01 20:58:33');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (274, 81, '应用诊断', 'connection', 'k8s:arthas', 2, 'k8s/arthas', 2, 8, '2026-03-04 16:04:01');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (275, 101, 'AI小助手', 'present', 'ops:ai', 2, 'ops/ai', 2, 3, '2026-03-14 19:07:49');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (276, 101, '飞书文档', 'present', 'ops:wiki', 2, 'ops/wiki', 2, 4, '2026-03-14 19:08:39');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (277, 251, '清空告警历史', '', 'monitor:alert:record:clear', 3, '', 2, 16, '2026-03-23 13:26:40');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (278, 251, '批量删除告警历史', '', 'monitor:alert:record:delete', 3, '', 2, 17, '2026-03-23 13:27:38');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (279, 78, '查看主机详情', '', 'cmdb:ecs:details', 3, '', 2, 11, '2026-03-23 15:04:04');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (280, 82, '查看凭据', '', 'cloud:k8s:get', 3, '', 2, 6, '2026-03-26 11:32:02');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (281, 83, '节点更多操作', '', 'k8s:node:actions', 3, '', 2, 3, '2026-03-26 11:38:55');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (282, 105, '命名空间更多操作', '', 'k8s:namespace:actions', 3, '', 2, 5, '2026-03-26 11:46:33');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (283, 93, '工作负载更多操作', '', 'k8s:workload:actions', 3, '', 2, 2, '2026-03-26 11:57:44');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (284, 106, '更多操作', '', 'k8s:network:actions', 3, '', 2, 3, '2026-03-26 12:17:19');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (285, 108, 'k8s存储操作', '', 'k8s:storage:actions', 3, '', 2, 1, '2026-03-26 12:22:33');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (286, 107, 'k8s配置更多操作', '', 'k8s:config:actions', 3, '', 2, 1, '2026-03-26 12:32:51');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (287, 107, '查看配置详情', '', 'k8s:config:get', 3, '', 2, 2, '2026-03-26 13:42:54');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (288, 108, '查看k8s存储配置', '', 'k8s:storage:get', 3, '', 2, 2, '2026-03-26 13:45:10');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (289, 275, '发送ai对话', '', 'tools:ai:post', 3, '', 2, 1, '2026-03-26 13:50:43');
INSERT INTO sys_menu (id, parent_id, menu_name, icon, value, menu_type, url, menu_status, sort, create_time) VALUES (290, 275, '清楚ai对话记录', '', 'tools:ai:clear-screen', 3, '', 2, 2, '2026-03-26 13:53:10');

-- sys_role_menu: 302 rows
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 72);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 80);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 78);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 149);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 150);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 151);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 152);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 153);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 154);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 155);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 165);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 166);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 241);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 243);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 279);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 88);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 89);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 90);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 91);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 245);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 246);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 95);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 146);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 147);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 148);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 217);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 218);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 219);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 220);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 221);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 222);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 81);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 82);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 167);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 168);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 169);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 170);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 171);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 280);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 83);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 172);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 173);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 281);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 105);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 178);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 179);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 180);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 182);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 282);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 93);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 185);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 283);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 192);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 193);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 194);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 195);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 196);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 106);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 197);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 203);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 284);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 108);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 285);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 288);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 107);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 286);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 287);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 274);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 109);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 242);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 110);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 142);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 143);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 144);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 145);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 162);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 163);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 164);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 111);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 139);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 140);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 141);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 160);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 161);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 207);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 223);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 224);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 225);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 208);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 226);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 227);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 228);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 212);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 213);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 229);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 230);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 231);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 232);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 233);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 234);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 235);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 216);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 236);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 237);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 238);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 239);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 240);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 251);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 252);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 254);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 256);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 257);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 258);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 259);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 260);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 261);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 262);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 263);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 264);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 265);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 266);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 267);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 277);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 278);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 268);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 269);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 273);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 270);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 271);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 272);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 97);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 99);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 136);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 137);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 138);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 156);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 157);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 98);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 133);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 134);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 135);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 130);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 131);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 132);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 159);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 101);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 103);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 102);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 126);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 127);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 128);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 129);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 275);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 289);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 290);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 276);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 4);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 6);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 16);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 17);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 18);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 60);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 7);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 21);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 22);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 23);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 24);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 8);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 26);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 27);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 28);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 10);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 32);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 33);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 34);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 215);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 84);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 85);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 123);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 124);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 125);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 86);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 122);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 119);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 120);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 121);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 250);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 104);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 115);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 117);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 118);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 244);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 44);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 45);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 47);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 113);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 73);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 46);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 49);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 62);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 96);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 247);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 72);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 149);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 150);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 154);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 165);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 89);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 146);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 218);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 167);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 168);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 170);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 172);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 173);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 178);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 179);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 180);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 182);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 185);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 193);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 195);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 197);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 203);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 288);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 287);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 274);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 142);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 144);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 162);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 139);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 140);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 160);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 223);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 224);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 226);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 227);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 229);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 233);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 236);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 240);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 256);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 257);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 258);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 273);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 270);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 136);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 137);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 156);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 133);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 130);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 132);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 159);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 103);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 127);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 276);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 16);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 125);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 122);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 118);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 73);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 62);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 96);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 247);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 80);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 78);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 88);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 95);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 81);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 82);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 83);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 105);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 93);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 106);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 108);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 107);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 109);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 110);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 111);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 207);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 208);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 212);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 213);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 216);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 251);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 268);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 97);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 99);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 98);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 101);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 102);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 4);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 6);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 84);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 85);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 86);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 104);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 44);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 45);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (13, 46);

SELECT setval(pg_get_serial_sequence('sys_post', 'id'), COALESCE((SELECT MAX(id) FROM sys_post), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dept', 'id'), COALESCE((SELECT MAX(id) FROM sys_dept), 1), true);
SELECT setval(pg_get_serial_sequence('sys_role', 'id'), COALESCE((SELECT MAX(id) FROM sys_role), 1), true);
SELECT setval(pg_get_serial_sequence('sys_admin', 'id'), COALESCE((SELECT MAX(id) FROM sys_admin), 1), true);
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), COALESCE((SELECT MAX(id) FROM sys_menu), 1), true);
