server:
  address: 0.0.0.0:8000
  model: debug
  enableSwagger: true
  publicUrl: "http://127.0.0.1:8080/"

db:
  dialects: postgres
  host: 127.0.0.1
  port: 5432
  db: autoops
  username: postgres
  password: postgres123456
  charset: utf8
  sslMode: disable
  migrationPath: ./migrations
  autoMigrate: true
  maxIdle: 50
  maxOpen: 150

redis:
  address: 127.0.0.1:6379
  password: "123456"

imageSettings:
  uploadDir: ./upload/

log:
  path: ./log
  name: sys
  model: console

monitor:
  prometheus:
    url: "http://127.0.0.1:9090"
  pushgateway:
    url: "http://127.0.0.1:9091"
  agent:
    heartbeat_server_url: "http://127.0.0.1:8000/api/v1/monitor/agent/heartbeat"
    heartbeat_token: "agent-heartbeat-token-2024"
  webhook:
    token: "webhook-notify-token-2024"
